name:                interacting-with-the-commandline
version:             0.1.0.0
github:              "malikiah/interacting-with-the-commandline"
license:             BSD3
author:              "Damian McCarthy"
maintainer:          "damianmmccarthy@protonmail.com"
copyright:           "BSD"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            value

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/malikiah/interacting-with-the-commandline#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  interacting-with-the-commandline:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - interacting-with-the-commandline

tests:
  interacting-with-the-commandline-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - interacting-with-the-commandline
