name:                lesson-sixteen-creating-types-with-and-and-or
version:             0.1.0.0
github:              "malikiah/lesson-sixteen-creating-types-with-and-and-or"
license:             BSD3
author:              "Damian McCarthy"
maintainer:          "damianmmccarthy@protonmail.com"
copyright:           "BSD"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            value

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/malikiah/lesson-sixteen-creating-types-with-and-and-or#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  lesson-sixteen-creating-types-with-and-and-or-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lesson-sixteen-creating-types-with-and-and-or

tests:
  lesson-sixteen-creating-types-with-and-and-or-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lesson-sixteen-creating-types-with-and-and-or
